// Comprehensive country list for citizenship selection.
// Israel is first; the rest are alphabetical by English name.
// Each entry: { value: ISO code, en: English name, he: Hebrew name }

export const COUNTRIES = [
  { value: "IL", en: "Israel", he: "ישראל" },
  { value: "US", en: "United States", he: "ארצות הברית" },
  { value: "GB", en: "United Kingdom", he: "הממלכה המאוחדת" },
  { value: "CA", en: "Canada", he: "קנדה" },
  { value: "AU", en: "Australia", he: "אוסטרליה" },
  { value: "NZ", en: "New Zealand", he: "ניו זילנד" },
  { value: "IE", en: "Ireland", he: "אירלנד" },
  { value: "AF", en: "Afghanistan", he: "אפגניסטן" },
  { value: "AL", en: "Albania", he: "אלבניה" },
  { value: "DZ", en: "Algeria", he: "אלג'יריה" },
  { value: "AD", en: "Andorra", he: "אנדורה" },
  { value: "AO", en: "Angola", he: "אנגולה" },
  { value: "AG", en: "Antigua and Barbuda", he: "אנטיגואה וברבודה" },
  { value: "AR", en: "Argentina", he: "ארגנטינה" },
  { value: "AM", en: "Armenia", he: "ארמניה" },
  { value: "AT", en: "Austria", he: "אוסטריה" },
  { value: "AZ", en: "Azerbaijan", he: "אזרבייג'ן" },
  { value: "BS", en: "Bahamas", he: "איי בהאמה" },
  { value: "BH", en: "Bahrain", he: "בחריין" },
  { value: "BD", en: "Bangladesh", he: "בנגלדש" },
  { value: "BB", en: "Barbados", he: "ברבדוס" },
  { value: "BY", en: "Belarus", he: "בלארוס" },
  { value: "BE", en: "Belgium", he: "בלגיה" },
  { value: "BZ", en: "Belize", he: "בליז" },
  { value: "BJ", en: "Benin", he: "בנין" },
  { value: "BT", en: "Bhutan", he: "בהוטן" },
  { value: "BO", en: "Bolivia", he: "בוליביה" },
  { value: "BA", en: "Bosnia and Herzegovina", he: "בוסניה והרצגובינה" },
  { value: "BW", en: "Botswana", he: "בוצוואנה" },
  { value: "BR", en: "Brazil", he: "ברזיל" },
  { value: "BN", en: "Brunei", he: "ברוניי" },
  { value: "BG", en: "Bulgaria", he: "בולגריה" },
  { value: "BF", en: "Burkina Faso", he: "בורקינה פאסו" },
  { value: "BI", en: "Burundi", he: "בורונדי" },
  { value: "CV", en: "Cape Verde", he: "כף ורדה" },
  { value: "KH", en: "Cambodia", he: "קמבודיה" },
  { value: "CM", en: "Cameroon", he: "קמרון" },
  { value: "CF", en: "Central African Republic", he: "הרפובליקה המרכז-אפריקאית" },
  { value: "TD", en: "Chad", he: "צ'אד" },
  { value: "CL", en: "Chile", he: "צ'ילה" },
  { value: "CN", en: "China", he: "סין" },
  { value: "CO", en: "Colombia", he: "קולומביה" },
  { value: "KM", en: "Comoros", he: "קומורו" },
  { value: "CG", en: "Congo", he: "קונגו" },
  { value: "CD", en: "DR Congo", he: "קונגו (דמוקרטית)" },
  { value: "CR", en: "Costa Rica", he: "קוסטה ריקה" },
  { value: "CI", en: "Ivory Coast", he: "חוף השנהב" },
  { value: "HR", en: "Croatia", he: "קרואטיה" },
  { value: "CU", en: "Cuba", he: "קובה" },
  { value: "CY", en: "Cyprus", he: "קפריסין" },
  { value: "CZ", en: "Czech Republic", he: "צ'כיה" },
  { value: "DK", en: "Denmark", he: "דנמרק" },
  { value: "DJ", en: "Djibouti", he: "ג'יבוטי" },
  { value: "DM", en: "Dominica", he: "דומיניקה" },
  { value: "DO", en: "Dominican Republic", he: "הרפובליקה הדומיניקנית" },
  { value: "EC", en: "Ecuador", he: "אקוודור" },
  { value: "EG", en: "Egypt", he: "מצרים" },
  { value: "SV", en: "El Salvador", he: "אל סלבדור" },
  { value: "GQ", en: "Equatorial Guinea", he: "גינאה המשוונית" },
  { value: "ER", en: "Eritrea", he: "אריתריאה" },
  { value: "EE", en: "Estonia", he: "אסטוניה" },
  { value: "SZ", en: "Eswatini", he: "אסוואטיני" },
  { value: "ET", en: "Ethiopia", he: "אתיופיה" },
  { value: "FJ", en: "Fiji", he: "פיג'י" },
  { value: "FI", en: "Finland", he: "פינלנד" },
  { value: "FR", en: "France", he: "צרפת" },
  { value: "GA", en: "Gabon", he: "גבון" },
  { value: "GM", en: "Gambia", he: "גמביה" },
  { value: "GE", en: "Georgia", he: "גאורגיה" },
  { value: "DE", en: "Germany", he: "גרמניה" },
  { value: "GH", en: "Ghana", he: "גאנה" },
  { value: "GR", en: "Greece", he: "יוון" },
  { value: "GD", en: "Grenada", he: "גרנדה" },
  { value: "GT", en: "Guatemala", he: "גואטמלה" },
  { value: "GN", en: "Guinea", he: "גינאה" },
  { value: "GW", en: "Guinea-Bissau", he: "גינאה-ביסאו" },
  { value: "GY", en: "Guyana", he: "גיאנה" },
  { value: "HT", en: "Haiti", he: "האיטי" },
  { value: "HN", en: "Honduras", he: "הונדורס" },
  { value: "HK", en: "Hong Kong", he: "הונג קונג" },
  { value: "HU", en: "Hungary", he: "הונגריה" },
  { value: "IS", en: "Iceland", he: "איסלנד" },
  { value: "IN", en: "India", he: "הודו" },
  { value: "ID", en: "Indonesia", he: "אינדונזיה" },
  { value: "IR", en: "Iran", he: "איראן" },
  { value: "IQ", en: "Iraq", he: "עיראק" },
  { value: "IT", en: "Italy", he: "איטליה" },
  { value: "JM", en: "Jamaica", he: "ג'מייקה" },
  { value: "JP", en: "Japan", he: "יפן" },
  { value: "JO", en: "Jordan", he: "ירדן" },
  { value: "KZ", en: "Kazakhstan", he: "קזחסטן" },
  { value: "KE", en: "Kenya", he: "קניה" },
  { value: "KI", en: "Kiribati", he: "קיריבטי" },
  { value: "KP", en: "North Korea", he: "צפון קוריאה" },
  { value: "KR", en: "South Korea", he: "דרום קוריאה" },
  { value: "XK", en: "Kosovo", he: "קוסובו" },
  { value: "KW", en: "Kuwait", he: "כווית" },
  { value: "KG", en: "Kyrgyzstan", he: "קירגיזסטן" },
  { value: "LA", en: "Laos", he: "לאוס" },
  { value: "LV", en: "Latvia", he: "לטביה" },
  { value: "LB", en: "Lebanon", he: "לבנון" },
  { value: "LS", en: "Lesotho", he: "לסוטו" },
  { value: "LR", en: "Liberia", he: "ליבריה" },
  { value: "LY", en: "Libya", he: "לוב" },
  { value: "LI", en: "Liechtenstein", he: "ליכטנשטיין" },
  { value: "LT", en: "Lithuania", he: "ליטא" },
  { value: "LU", en: "Luxembourg", he: "לוקסמבורג" },
  { value: "MO", en: "Macau", he: "מקאו" },
  { value: "MG", en: "Madagascar", he: "מדגסקר" },
  { value: "MW", en: "Malawi", he: "מלאווי" },
  { value: "MY", en: "Malaysia", he: "מלזיה" },
  { value: "MV", en: "Maldives", he: "האיים המלדיביים" },
  { value: "ML", en: "Mali", he: "מאלי" },
  { value: "MT", en: "Malta", he: "מלטה" },
  { value: "MR", en: "Mauritania", he: "מאוריטניה" },
  { value: "MU", en: "Mauritius", he: "מאוריציוס" },
  { value: "MX", en: "Mexico", he: "מקסיקו" },
  { value: "FM", en: "Micronesia", he: "מיקרונזיה" },
  { value: "MD", en: "Moldova", he: "מולדובה" },
  { value: "MC", en: "Monaco", he: "מונקו" },
  { value: "MN", en: "Mongolia", he: "מונגוליה" },
  { value: "ME", en: "Montenegro", he: "מונטנגרו" },
  { value: "MA", en: "Morocco", he: "מרוקו" },
  { value: "MZ", en: "Mozambique", he: "מוזמביק" },
  { value: "MM", en: "Myanmar", he: "מיאנמר" },
  { value: "NA", en: "Namibia", he: "נמיביה" },
  { value: "NR", en: "Nauru", he: "נאורו" },
  { value: "NP", en: "Nepal", he: "נפאל" },
  { value: "NL", en: "Netherlands", he: "הולנד" },
  { value: "NI", en: "Nicaragua", he: "ניקרגואה" },
  { value: "NE", en: "Niger", he: "ניז'ר" },
  { value: "NG", en: "Nigeria", he: "ניגריה" },
  { value: "MK", en: "North Macedonia", he: "צפון מקדוניה" },
  { value: "NO", en: "Norway", he: "נורווגיה" },
  { value: "OM", en: "Oman", he: "עומאן" },
  { value: "PK", en: "Pakistan", he: "פקיסטן" },
  { value: "PW", en: "Palau", he: "פלאו" },
  { value: "PS", en: "Palestine", he: "פלסטין" },
  { value: "PA", en: "Panama", he: "פנמה" },
  { value: "PG", en: "Papua New Guinea", he: "פפואה גינאה החדשה" },
  { value: "PY", en: "Paraguay", he: "פרגוואי" },
  { value: "PE", en: "Peru", he: "פרו" },
  { value: "PH", en: "Philippines", he: "הפיליפינים" },
  { value: "PL", en: "Poland", he: "פולין" },
  { value: "PT", en: "Portugal", he: "פורטוגל" },
  { value: "QA", en: "Qatar", he: "קטאר" },
  { value: "RO", en: "Romania", he: "רומניה" },
  { value: "RU", en: "Russia", he: "רוסיה" },
  { value: "RW", en: "Rwanda", he: "רואנדה" },
  { value: "SM", en: "San Marino", he: "סן מרינו" },
  { value: "ST", en: "São Tomé and Príncipe", he: "סאו טומה ופרינסיפה" },
  { value: "SA", en: "Saudi Arabia", he: "ערב הסעודית" },
  { value: "SN", en: "Senegal", he: "סנגל" },
  { value: "RS", en: "Serbia", he: "סרביה" },
  { value: "SC", en: "Seychelles", he: "סיישל" },
  { value: "SL", en: "Sierra Leone", he: "סיירה לאונה" },
  { value: "SG", en: "Singapore", he: "סינגפור" },
  { value: "SK", en: "Slovakia", he: "סלובקיה" },
  { value: "SI", en: "Slovenia", he: "סלובניה" },
  { value: "SB", en: "Solomon Islands", he: "איי שלמה" },
  { value: "SO", en: "Somalia", he: "סומליה" },
  { value: "ZA", en: "South Africa", he: "דרום אפריקה" },
  { value: "SS", en: "South Sudan", he: "דרום סודאן" },
  { value: "ES", en: "Spain", he: "ספרד" },
  { value: "LK", en: "Sri Lanka", he: "סרי לנקה" },
  { value: "SD", en: "Sudan", he: "סודאן" },
  { value: "SR", en: "Suriname", he: "סורינאם" },
  { value: "SE", en: "Sweden", he: "שוודיה" },
  { value: "CH", en: "Switzerland", he: "שוויץ" },
  { value: "SY", en: "Syria", he: "סוריה" },
  { value: "TW", en: "Taiwan", he: "טייוואן" },
  { value: "TJ", en: "Tajikistan", he: "טג'יקיסטן" },
  { value: "TZ", en: "Tanzania", he: "טנזניה" },
  { value: "TH", en: "Thailand", he: "תאילנד" },
  { value: "TL", en: "East Timor", he: "מזרח טימור" },
  { value: "TG", en: "Togo", he: "טוגו" },
  { value: "TO", en: "Tonga", he: "טונגה" },
  { value: "TT", en: "Trinidad and Tobago", he: "טרינידד וטובגו" },
  { value: "TN", en: "Tunisia", he: "תוניסיה" },
  { value: "TR", en: "Turkey", he: "טורקיה" },
  { value: "TM", en: "Turkmenistan", he: "טורקמניסטן" },
  { value: "TV", en: "Tuvalu", he: "טובאלו" },
  { value: "UG", en: "Uganda", he: "אוגנדה" },
  { value: "UA", en: "Ukraine", he: "אוקראינה" },
  { value: "AE", en: "United Arab Emirates", he: "איחוד האמירויות" },
  { value: "UY", en: "Uruguay", he: "אורוגוואי" },
  { value: "UZ", en: "Uzbekistan", he: "אוזבקיסטן" },
  { value: "VU", en: "Vanuatu", he: "ונואטו" },
  { value: "VA", en: "Vatican City", he: "ותיקן" },
  { value: "VE", en: "Venezuela", he: "ונצואלה" },
  { value: "VN", en: "Vietnam", he: "וייטנאם" },
  { value: "YE", en: "Yemen", he: "תימן" },
  { value: "ZM", en: "Zambia", he: "זמביה" },
  { value: "ZW", en: "Zimbabwe", he: "זימבבואה" },
];